FROM ubuntu:xenial

RUN apt-get update && \
    apt-get install -y build-essential cmake qt5-default libqt5opengl5-dev && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /root/build
ADD src /root/src
WORKDIR /root/build
RUN cmake ../src && make

CMD /bin/bash
